### ISSUE TITLE
Fresh Install of usercake and your forum, but its not working.

### ISSUE THREAD

**Issue by NotLazy** [davarravad/usercakeforum#2]
ok heres what i did:
-i uploaded usercake and installed it
-after successful installation i uploaded your forum
-i added "Forum.php" as a navigation in left-nav.php
-i clicked on it, and was taken to the page where i was presented with a box labeled "Forum"
-there was an error because i had forgotten to add the database stuff
-i added the database stuff from the readme.md file and then went back to the forum page
-inside the forum box it said "Fatal error: Call to undefined method mysqli_result::fetch_all() in /home/########/public_html/forum/forum_admin_funcs.php on line 72"

Why is this?
for me, line 72 reads:
$arr = $result->fetch_all(MYSQLI_BOTH);

**Comment by davarravad** [comment]
I forgot that I had to install mysqlnd to get this function to work.  I will find a better way to work around that in the future, but thank you for letting me know about this issue.

Here is the php.net documentation regarding the installation of mysqlnd:
http://www.php.net/manual/en/mysqlnd.install.php

I will update the readme.  Thanks.

**Comment by davarravad** [comment]
Ok.  I updated the code to hopefully work without having to install mysqlnd.  I have not yet released it.  Can you try the main code and let me know if that fixed the issue?

However I did notice there is an error when the no topics are created, but will work on that later.

**Comment by NotLazy** [comment]
i cant actually install mysqlnd, my host doesnt support it. can you possibly work on that no topic bug, since i have no idea what exactly i'd use for syntax on creating a topic through phpmyadmin

**Comment by davarravad** [comment]
It will display the error, but you can still create a new topic in the Forum.  Once a topic exists error goes away.  Did the update at least work?

**Comment by davarravad** [comment]
I was able to figure out the issue that cause that error.  Should be good to go.  Also made some other updates.  New version is released.
