### ISSUE TITLE
Sorry, Tokens do not match! Please go back and try again. 

### ISSUE THREAD

**Issue by NotLazy** [davarravad/usercakeforum#3]
as the title says

im logged in as an admin, whats wrong here?

**Comment by NotLazy** [comment]
also the new version did fix the error i was encountering, thanks

**Comment by NotLazy** [comment]
ill mention its still a fresh install of both. you can check out whats wrong at http://kadcraftnetwork.site40.net/ and can login with
user: admin
pass: password

just click forums once logged in

**Comment by davarravad** [comment]
Open up the forum.php file.

Turn the debug settings on.
$debug_website = "TRUE";

The token script makes sure that the url in admin_config are same as url.

**Comment by davarravad** [comment]
Ok.  For some reason the url's did not match.  I updated the url in the admin_config on your site and it allowed me to create a new Title.

**Comment by davarravad** [comment]
Well I have found another issue.  I will see if I can figure it out.  The forum is only displaying the first title.

**Comment by davarravad** [comment]
I updated the forum/main.php to fix the title issue.

**Comment by davarravad** [comment]
Once you get a chance to upload the new forum/main.php file let me know if it works better.

Thanks for trying the forum.

**Comment by davarravad** [comment]
I added the ability to lock topics.  Also updated the uc_forum_posts sql structure.

**Comment by NotLazy** [comment]
i'd like to note that the site its tested on isnt a live site. my live site is located at notecraft.host22.com

**Comment by NotLazy** [comment]
alright uploading the new forum stuff now..
upload complete.

**Comment by NotLazy** [comment]
whoops.. heh.. deleted a title and now an error is poping up

**Comment by NotLazy** [comment]
alright so, because im not seeing a reason for the error message "Forums Are Not In Order. Admin Must Fix This in SQL! Otherwise mess with order. Reason for this message: Admin deleted a title. " i'm going to remove it in the public version i post on my site soon. please do stop me if there is a reason i shouldn't remove it?

**Comment by NotLazy** [comment]
ok, so i've created some catagories(dunno why you called em that but..) and one post.. and all im wondering right now is.. how the hell do i lock a topic?

**Comment by NotLazy** [comment]
Nevermind, i found it.

**Comment by davarravad** [comment]
You can hide that error.  It just shows up if the cat_sort_id is not right.  I have yet to come up with a fix that will automatically fix that.  It should only show up for admins.

**Comment by davarravad** [comment]
If you have any ideas for future updates or other suggestions for the forum you can post them on http://www.thedavar.net/Forum/

**Comment by NotLazy** [comment]
ok well umm how do i change the profile link? right now if you click on admin it redirects to /members/1 but on my site its /account.php?id=1

**Comment by NotLazy** [comment]
also does the "edited x minutes ago" show for everyone?

**Comment by davarravad** [comment]
In display_topic.php line 115 you should see:

``` php
echo "<br><a href='${site_url_link}member/$f_p_user_id/'>$f_p_user_name</a> ";
```

Just update it to reflect your site.  

Also located in the following:
display_topic.php   line 351
forum_display.php   line 156 & 187
reply_topic.php   line 19

**Comment by davarravad** [comment]
Yes the edited min ago is displayed for everyone.

**Comment by davarravad** [comment]
I just updated the readme to reflect this, but there is a forum_recent.php file included.

It shows the 10 most recent posts and replies on the forum.

I did not updated the style on it, but you should be able to copy the css from the Forum.php file.

You can include it anywhere on your site.  I put mine in the navigation bar.

**Comment by NotLazy** [comment]
you should add the ability to remove replies..

**Comment by davarravad** [comment]
Where at?

**Comment by NotLazy** [comment]
in posts.. like uhm..
Forum>Off-Topic>Off-Topic Rules>a random post
i should be able to have a button, per say beside edit(assuming admins can edit posts that they dont own) that says delete, and users can delete their own posts.

**Comment by NotLazy** [comment]
also how do i disable the "edited x minutes ago" xD

im trying to find it and comment it away

**Comment by davarravad** [comment]
Ah gotcha.   I will build a forum settings page when I get a chance.
I will make sure to include these options.

I have the delete buttons on my to do list.  Right now only the user that owns the post or post reply can edit the post.  I will work in a fix for the edit.  Give me a few min.

**Comment by davarravad** [comment]
The edited x ago is in display_topic.php around lines 121 and 357

```php
// Display how long ago this was posted
$timestart = "$f_p_timestamp";  //Time of post
require_once "models/timediff.php";
echo "<br><font color=green> " . dateDiff("now", "$timestart", 1) . " ago</font> ";
```

```php
// Display how long ago this was posted
$timestart = "$rf_p_timestamp";  //Time of post
require_once "models/timediff.php";
echo "<br><font color=green> " . dateDiff("now", "$timestart", 1) . " ago</font> ";
```

**Comment by NotLazy** [comment]
uhm i think those are the post dates not the edited dates :s

**Comment by NotLazy** [comment]
just checked, neither of them remove the edited x minutes ago

**Comment by davarravad** [comment]
oh sorry... that is the created ago... 

Trying to multitask and not doing well at it... lol

display_topic.php around lines 146 & 375

``` php
                if($f_p_edit_date != NULL){
                    // Display how long ago this was posted
                    $timestart = "$f_p_edit_date";  //Time of post
                    require_once "models/timediff.php";
                    echo "<font color=red>Edited</font><br><font color=red> " . dateDiff("now", "$timestart", 1) . " ago</font> <br><br>";
                }
```

**Comment by NotLazy** [comment]
thanks ^-^
for now im just commenting it away but in the future maybe ill change it to only display to admins

**Comment by NotLazy** [comment]
well, from what i've seen so far this is an epic forum, and i love it.
+1 for this forum!
(might i suggest an auto installer like usercakes for even simpler simplicity?)

**Comment by davarravad** [comment]
In time.  lol

If you want to allow mods and admins to edit any posts or replies just edit in the following:
display_topic.php around line 153

``` php
if($f_p_user_id == $userIdme){

if($f_p_user_id == $userIdme || userCheckForumAdmin() || userCheckForumMod()){
```

and around line 382

``` php
if($rf_p_user_id == $userIdme){

if($rf_p_user_id == $userIdme || userCheckForumAdmin() || userCheckForumMod()){
```

**Comment by davarravad** [comment]
Also you can edit the forum moderators by their admin_permission id in the forum_admin_funcs.php file.  By default it is setup for ID# 4.  

``` php
function userCheckForumMod(){
    // Check if user is logged in
    if(isUserLoggedIn())
    {
        // Moderator users permissions id is 4
        global $loggedInUser;
        if ($loggedInUser->checkPermission(array(4)) == true){
            // User is Mod
            return 1;
        }
        else
        {
            // User is NOT Mod
            return 0;
        }
    }
}
```

You can just edit the array to as many ids as you like

``` php
if ($loggedInUser->checkPermission(array(3,4,6,32,10)) == true){
```

Just an example.

**Comment by NotLazy** [comment]
yea i had already found the mod thing

**Comment by davarravad** [comment]
Ok cool.  Just making sure.

**Comment by NotLazy** [comment]
thanks though

**Comment by davarravad** [comment]
You bet.  Let me know if you have any other issues.
