### ISSUE TITLE
uploaded to live host and instantly broken

### ISSUE THREAD

**Issue by NotLazy** [davarravad/usercakeforum#4]
i copied everything directly from the previous host, and now its not working.

MySQL: Check.
All forum stuffz: Check
db-settings: Check, they work else where
Error: Fatal error: Call to a member function fetch_assoc() on boolean in C:\xampp\htdocs\forum\main.php on line 30

**Comment by davarravad** [comment]
Does your main.php look like this?  I updated the code for an error like this.  

``` php
// Get all Categories from database
    $query_title = "SELECT * FROM ".$db_table_prefix."forum_cat WHERE `forum_name`='$stc_page_sel' GROUP BY forum_title ORDER BY `".$db_table_prefix."forum_cat`.`forum_order_title` ASC ";
    $result_title = $mysqli->query($query_title);
    while ($row_title = $result_title->fetch_assoc()) {
        $f_title = $row_title['forum_title'];
        $f_id = $row_title['forum_id'];
        $f_order_title = $row_title['forum_order_title'];
```

**Comment by NotLazy** [comment]
dunno lemme check. assuming thats around line 30?

**Comment by NotLazy** [comment]
```
$query_title = "SELECT * FROM ".$db_table_prefix."forum_cat WHERE `forum_name`='$stc_page_sel' GROUP BY forum_title ORDER BY `".$db_table_prefix."forum_cat`.`forum_order_title` ASC ";
$result_title = $mysqli->query($query_title);
while ($row_title = $result_title->fetch_assoc()) {
    $f_title = $row_title['forum_title'];
    $f_id = $row_title['forum_id'];
    $f_order_title = $row_title['forum_order_title'];
```

**Comment by NotLazy** [comment]
looks to me like it matches .-.

**Comment by davarravad** [comment]
Yeah it matches.  Let me see if I can get that same error.

**Comment by NotLazy** [comment]
if you need i can make you a phpmyadmin and ftp account so you can cross check everything

**Comment by NotLazy** [comment]
ill admit im not the best with phpmyadmin accounts though

**Comment by davarravad** [comment]
Sure.  SignUp/Login to my website http://www.thedavar.net and send me a PM there.

**Comment by davarravad** [comment]
once logged in just put this URL in your browser.

http://www.thedavar.net/message/?mes=newmessage&mto=1

That will automatically setup a new message to me.

**Comment by NotLazy** [comment]
im smart enough to not need a direct link *challange accepted meme*

lol..

**Comment by davarravad** [comment]
It was a ".$db_table_prefix." error.... fixed yay!
